config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "pages#home" , as: "home"

  get "/produit/:id", to: "pages#produit" , as: "product"

  get "/admin", to: "pages#admin" , as: "admin"

  get "/espacepersonnelle", to: "pages#espacepersonnelle", as: "espace"

  post "/achatproduit/:id", to: "pages#achatproduit", as: "achatproduit"
  


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/DbPerformanceTracker.rb
class DbPerformanceTracker
    def self.setup
      @queries = []
  
      ActiveSupport::Notifications.subscribe('sql.active_record') do |_, started, finished, _, payload|
        duration = (finished - started) * 1000
        @queries << duration if payload[:name] != 'SCHEMA'
      end
    end
  
    def self.total_duration
      @queries.sum
    end
  
    def self.reset
      @queries = []
    end
  end
    

app/models/achat.rb
class Achat < ApplicationRecord
    belongs_to :visiteur, foreign_key: 'visiteur_id'
    belongs_to :ressource, foreign_key: 'produit_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ressource.rb
class Ressource < ApplicationRecord
    has_many :achats, foreign_key: :produit_id
    has_many :visiteurs, through: :achats
end

app/models/visiteur.rb
class Visiteur < ApplicationRecord
    has_many :achats, foreign_key: 'visiteur_id'
    has_many :ressources, through: :achats, source: :ressource
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController<ApplicationController
  before_action :set_visitor_id, :measure_backend_performance , :start_db_tracking
  after_action :log_backend_duration, :stop_db_tracking
  caches_action :home, :produit, :espacepersonnelle,:achatproduit ,expires_in: 5.minutes
  
  def home 
    @ressources = Ressource.all

    visiteur_id = request.remote_ip
    visiteur=Visiteur.find_by(visiteur_id: visiteur_id)
    achats = visiteur.achats
    if achats.any?
      puts "Achats effectués par le visiteur #{visiteur.visiteur_id} :"
      achats.each do |achat|
        puts "Produit ID : #{achat.produit_id}, Créé à : #{achat.created_at}"
      end
    end
    ressource_ids_achetees = achats.pluck(:produit_id)
    @ressources = Ressource.where.not(id: ressource_ids_achetees )
    expires_in 1.hour, public: true
  end

  def produit
      @ressource_id = params[:id]
      @ressource = Ressource.find_by(id: @ressource_id)
      expires_in 1.hour, public: true
  end

  def espacepersonnelle
    visiteur_id = request.remote_ip
    visiteur=Visiteur.find_by(visiteur_id: visiteur_id)
    Rails.logger.debug { "Ressource : #{visiteur_id}" }
    if visiteur
      achats = visiteur.achats
      ressource_ids_achetees = achats.pluck(:produit_id)
      @ressources_achetees  = Ressource.where(id: ressource_ids_achetees )
      Rails.logger.debug { "Ressource : #{@ressources_achetees}" }
    else
      @ressources_achetees = []
    end
    expires_in 1.hour, public: true
  end

  def admin
    @total_visiteurs = Visiteur.count
    @total_achats = Achat.count
    @backend_duration = flash[:backend_duration]
    @bdd_duration = flash[:total_duration]
    expires_in 1.hour, public: true
  end

  def achatproduit
    @ressource_id = params[:id]
    @ressource = Ressource.find_by(id: @ressource_id)
  
    if @ressource.nil?
      flash[:error] = "Produit non trouvé"
      redirect_to root_path and return
    end

    visiteur_id = request.remote_ip
    visiteur=Visiteur.find_by(visiteur_id: visiteur_id)

    if visiteur.nil?
      flash[:error] = "Visiteur non trouvé"
      redirect_to root_path and return
    end

    achat=Achat.find_or_create_by(
      visiteur_id: visiteur.id, 
      produit_id: @ressource_id
    )
    if achat.persisted?
      Rails.logger.debug { "Succes de validation : #{achat.errors.full_messages}" }
      flash[:success] = "Achat enregistré avec succès"
    else
      Rails.logger.debug { "Erreurs de validation : #{achat.errors.full_messages}" }
      flash[:error] = "Erreur lors de l'enregistrement de l'achat"
    end

    achats = visiteur.achats
    ressource_ids_achetees = achats.pluck(:produit_id)
    @ressources = Ressource.where.not(id: ressource_ids_achetees)
    flash[:success] = "Achat enregistré avec succès"
    expires_in 1.hour, public: true
    
  end

  private

  def set_visitor_id
    ip_address = request.remote_ip
    unless Visiteur.exists?(visiteur_id: ip_address)
      Visiteur.create(visiteur_id: ip_address)
    end
  end
  
  def measure_backend_performance
    @start_time = Time.now
  end

  def log_backend_duration
    end_time = Time.now
    @backend_duration = (end_time - @start_time) * 1000 # En millisecondes
    flash[:backend_duration] = @backend_duration
    Rails.logger.info "Durée du backend pour l'action #{action_name}: #{@backend_duration} ms"
  end

end

def start_db_tracking
  DbPerformanceTracker.setup
end

def stop_db_tracking
  @total_duration = DbPerformanceTracker.total_duration
  Rails.logger.info "Durée du bdd pour l'action #{action_name}: #{@total_duration} ms"
  flash[:total_duration] = @total_duration
  DbPerformanceTracker.reset
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title><%= content_for(:title) || "Miniirawo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <style>
      * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
      }

      body {
        font-family: 'Arial', sans-serif;
        background: radial-gradient(circle at top, #ffffff, #e6e6e6, #cccccc);
        color: black;
        text-align: center;
        min-height: 100vh;
        display: flex;
        flex-direction: column;
        justify-content: start;
        align-items: center;
        overflow-y: auto; 
      }

      .header {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        max-width: 450px;
        padding: 10px 10px;
        background-color: rgba(0, 0, 0, 0.3);
        border-radius: 45px;
        box-shadow: 0 5px 20px rgba(0, 0, 0, 0.3);
        margin-top: 20px;
        font-weight: bold;
      }

      .logo-img {
        width: 120px;
        height: auto;
        display: block;
      }

      .nav-links {
        display: flex;
        gap: 30px;
        font-size: 16px;
      }

      .nav-links a {
        color: #ffffff;
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 6px;
        transition: all 0.3s ease;
        font-weight: 700;
      }

      .nav-links a:hover {
        background-color: rgba(255, 255, 255, 0.2);
        color: #ffda79;
      }

      .cta-login {
        padding: 10px 20px;
        background: linear-gradient(90deg, #ffda79, #ffe57a);
        color: #3b0066;
        font-weight: bold;
        border-radius: 80px;
        text-decoration: none;
        box-shadow: 0 3px 10px rgba(255, 223, 138, 0.5);
        transition: all 0.3s ease;
      }
    </style>
  </head>

  <body>
    <div class="header">
    <%= link_to image_tag("irawo-logo.png", alt: "Irawo Logo",class:"logo-img") %>
      <div class="nav-links">
        <a href="<%= home_path %>">Ressources</a>
        <a href="<%= espace_path %>" class="cta-login">Votre Espace</a>
      </div>
   </div>
    <%= yield %>
  </body>
</html>


<script>
document.addEventListener("DOMContentLoaded", () => {
  const timing = performance.timing;

  const frontEndTime = timing.responseEnd - timing.navigationStart;

  console.log("Front-End Time:", frontEndTime);

  const frontEndElement = document.getElementById("front-end-time");

  if (frontEndElement) {
    frontEndElement.textContent = `${frontEndTime} ms`;
  } else {
    console.error("L'élément avec l'ID 'front-end-time' est manquant.");
  }

  });

</script>

app/views/pages/achatproduit.html.erb
<div class="filters-products-container">
<div class="filters">
  <h3>Filtres</h3>
  <label>
    <input type="checkbox" name="category" value="formation"> Formations
  </label>
  <label>
    <input type="checkbox" name="category" value="ebook"> eBooks
  </label>
  <label>
    <input type="checkbox" name="category" value="coaching"> Coaching
  </label>
  <h3 class="left-space-filter">Intervalle de prix</h3>
  <label>
    <input type="checkbox" name="price" value="0-50"> 0€ - 50€
  </label>
  <label>
    <input type="checkbox" name="price" value="51-100"> 51€ - 100€
  </label>
  <label>
    <input type="checkbox" name="price" value="101-200"> 101€ - 200€
  </label>
  <label>
    <input type="checkbox" name="price" value="201-500"> 201€ - 500€
  </label>
  <label>
    <input type="checkbox" name="price" value="500+"> 500€ et plus
  </label>
</div>


<section class="products">
  <% @ressources.each do |ressource| %>
    <div class="product-card">
      <%= link_to image_tag(ressource.lienImage, alt: "Produit") %>
      <h3> <%= ressource.titre %> </h3>
      <p><%= ressource.description %></p>
      <p><strong>Prix : <%= number_to_currency(ressource.prix) %></strong></p>
      <button><a href="<%= product_path %>">Voir Produit</a></button>
      <button><a href="<%= achatproduit_path(id: ressource.id) %>">Acheter</a></button>
    </div>
  <% end %>
</section>
</div>

<div class="footer">
Plus de 100000 élèves nous on fait confiance
<div class="trusted-avatars">
    <%= link_to image_tag("pp-photo-1.jpg", alt: "Creator 1") %>
    <%= link_to image_tag("pp-photo-2.jpg", alt: "Creator 2") %>
    <%= link_to image_tag("pp-photo-3.jpg", alt: "Creator 3") %>
</div>
</div>

<%= stylesheet_link_tag "home", media: "all" %>

app/views/pages/admin.html.erb
<div class="container">
<h1>Dashboard Admin</h1>
<section class="kpi">
  <div class="kpi-card">
    <h3> <%= @total_visiteurs %> </h3>
    <p>Nombre de visiteurs</p>
  </div>
  <div class="kpi-card">
    <h3><%= @total_achats %> </h3>
    <p>Nombre de produits vendus</p>
  </div>
</section>

<h1>Performances</h1>
<section class="kpi">
  <div class="kpi-card">
    <h3> <%= @backend_duration %> ms </h3>
    <p>Backend performance</p>
  </div>
  <div class="kpi-card">
  <h3 id="front-end-time"> </h3>
  <p>Frontend performance</p>
  </div>
  <div class="kpi-card">
  <h3> <%= @bdd_duration %> ms</h3>
  <p>BDD performance</p>
</div>
</section>

</div>

<%= stylesheet_link_tag "admin", media: "all" %>

app/views/pages/espacepersonnelle.html.erb
<h1 style="text-align: center; margin: 20px 0;">Espaces de Ressources Achetées</h1>
<div class="container">
  <div class="filters-products-container">
    <section class="products">
    
    <% if @ressources_achetees.any? %>
      <% @ressources_achetees.each do |ressource| %>
        <div class="product-card">
          <%= link_to image_tag(ressource.lienImage, alt: "Produit") %>
          <h3> <%= ressource.titre %> </h3>
          <p><%= ressource.description %></p>
          <p><strong>Prix : <%= number_to_currency(ressource.prix) %></strong></p>
          <p><strong>Vous pouvez telecharger la resource ici : <%= ressource.lien%></strong></p>
          <button><a href="<%= product_path(id: ressource.id) %>">Voir Produit</a></button>
        </div>
      <% end %>
    <% else %>
      <p>Aucune ressource achetée.</p>
    <% end %>
    </section>
  </div>
</div>


<%= stylesheet_link_tag "espacepersonnelle", media: "all" %>

app/views/pages/home.html.erb
<div class="filters-products-container">
  <div class="filters">
    <h3>Filtres</h3>
    <label>
      <input type="checkbox" name="category" value="finance"> Finance
    </label>
    <label>
      <input type="checkbox" name="category" value="marketin"> Marketin
    </label>
    <label>
      <input type="checkbox" name="category" value="education"> Education
    </label>
    <h3 class="left-space-filter">Intervalle de prix</h3>
    <label>
      <input type="checkbox" name="price" value="0-50"> 0€ - 50€
    </label>
    <label>
      <input type="checkbox" name="price" value="51-100"> 51€ - 100€
    </label>
    <label>
      <input type="checkbox" name="price" value="101-200"> 101€ - 200€
    </label>
    <label>
      <input type="checkbox" name="price" value="201-500"> 201€ - 500€
    </label>
    <label>
      <input type="checkbox" name="price" value="500+"> 500€ et plus
    </label>
  </div>

  <section class="products">
    <% @ressources.each do |ressource| %>
      <div class="product-card">
        <%= link_to image_tag(ressource.lienImage, alt: "Produit") %>
        <h3> <%= ressource.titre %> </h3>
        <p class="prix" data-price="<%= ressource.prix %>">
          <strong>Prix : <%= number_to_currency(ressource.prix) %></strong>
        </p>
        <p class="category" data-category="<%= ressource.categorie %>">
          Category : <%= ressource.categorie %>
        </p>
        <button><a href="<%= product_path(id: ressource.id) %>">Voir Produit</a></button>
        <%= form_with url: achatproduit_path(id: ressource.id), method: :post, class: "inline-form" do %>
          <button type="submit">Acheter</button>
        <% end %>
      </div>
    <% end %>
  </section>
</div>

<div class="footer">
  Plus de 100000 élèves nous ont fait confiance
  <div class="trusted-avatars">
      <%= link_to image_tag("pp-photo-1.jpg", alt: "Creator 1") %>
      <%= link_to image_tag("pp-photo-2.jpg", alt: "Creator 2") %>
      <%= link_to image_tag("pp-photo-3.jpg", alt: "Creator 3") %>
  </div>
</div>

<%= stylesheet_link_tag "home", media: "all" %>
<script>
  document.addEventListener("DOMContentLoaded", () => {
    const categoryFilters = document.querySelectorAll("input[name='category']");
    const priceFilters = document.querySelectorAll("input[name='price']");
    const productCards = document.querySelectorAll(".product-card");

    const filterProducts = () => {
      const activeCategories = Array.from(categoryFilters)
        .filter((checkbox) => checkbox.checked)
        .map((checkbox) => checkbox.value.toLowerCase()); // On met les valeurs en minuscule

      const activePrices = Array.from(priceFilters)
        .filter((checkbox) => checkbox.checked)
        .map((checkbox) => checkbox.value);

      productCards.forEach((card) => {
        const category = card.querySelector(".category").dataset.category.toLowerCase(); // Mettre en minuscule
        const price = parseFloat(card.querySelector(".prix").dataset.price);

        const matchesCategory =
          activeCategories.length === 0 || activeCategories.includes(category);
        const matchesPrice =
          activePrices.length === 0 ||
          activePrices.some((range) => {
            if (range === "500+") return price > 500;
            const [min, max] = range.split("-").map(Number);
            return price >= min && price <= max;
          });
          
        card.style.display = matchesCategory && matchesPrice ? "block" : "none";
      });
    };
    categoryFilters.forEach((checkbox) =>
      checkbox.addEventListener("change", filterProducts)
    );
    priceFilters.forEach((checkbox) =>
      checkbox.addEventListener("change", filterProducts)
    );

    console.log("Produits chargés :", productCards);
  });
</script>

app/views/pages/produit.html.erb
<h1><%= @ressource.titre %></h1>

<div class="product-presentation">
    <%= link_to image_tag(@ressource.lienImage, alt: "Formation JavaScript") %>
  <p>
    <%= @ressource.description %>
  </p>
  <p class="price">Prix :<%= number_to_currency(@ressource.prix) %></p>
  <p>lien Access fichier:<%= number_to_currency(@ressource.prix) %></p>
</div>

<%= stylesheet_link_tag "produit", media: "all" %>
      